### PR TITLE
Second pass code review

### PR DESCRIPTION
**Pull request by nicholastmosher**
I hope you don't mind that I keep messing with things, but I really like refactoring :)

I did two things here. First, I noticed that you were instantiating `mongodb::Client` more than once, so I factored those out to the top-level. I did this with the `reqwest::Client` too because it's good practice to pass in your external resources from the outside. You'll notice that anywhere you need those client objects, a reference to them is passed down through the functions to that site. This is a step in the right direction, but the next step would be to create a custom struct that holds a reference to the clients, then to make all of your functions belong to that struct.

The next thing was that I split your crate into two halves, a library and a binary. If you recall, when you first do `cargo new shelflife`, you can either specify `--bin` (which is done implicitly) to create a binary,  or `--lib` to create a library. Well fun fact, you can actually have the same crate serve as a library and a binary at the same time (see the changes to Cargo.toml, pretty easy actually). The advantage of this is that you separate the core logic from your presentation (think back to any CS class, you've got your Model-View-Controller pattern, your "model" and "control" go into the library, and your "view" goes into the binary). The end goal with this separation is that all of your data structures and functions go into your library, and all of your command-line interaction (ideally _all_ of your print statements, for example) go into the binary half.

### CODE REVIEW

**Comment by WillNilges** [comment]
Fascinating. Didn't know this was a thing! This is very much what I had in mind for how I wanted things structured, though. I've got a few more things I wanna wrap up, but then I'd like to merge this.

**Comment by nicholastmosher** [comment]
Rebased against your latest changes. Pretty sure I got everything right because it builds, but do you want to check it out by running it? (I don't have a key)

**Comment by WillNilges** [comment]
Looks like it runs! I'm gonna merge it.

**Review by WillNilges — APPROVED** [review]
Pretty advanced. I dig it.

**Pull request merged**
